-- =====================================================================
-- SEED: 20 principais cartões de crédito do Brasil (referência editorial 2026)
-- =====================================================================
-- IMPORTANTE:
--  1) affiliate_url está com o SITE OFICIAL de cada emissor (placeholder).
--     Troque pelo SEU link de afiliado para ganhar comissão (CPA).
--  2) Anuidades/benefícios mudam — revise antes de divulgar (conteúdo financeiro).
--  3) rating é editorial (reputação geral) — ajuste como quiser.
--  4) INSERT OR IGNORE: rodar de novo não duplica (slug é único).
-- Fontes: idinheiro.com.br, melhoresdestinos.com.br, melhorescartoes.com.br (jan/2026)

INSERT OR IGNORE INTO credit_cards
  (slug, name, issuer, image_url, tagline, annual_fee, benefits, badges, rating, affiliate_url, cta_label, category, featured, sort_order, active, created_at, updated_at)
VALUES
('nubank','Nubank','Nubank',NULL,'O roxinho: conta e cartão sem tarifas, tudo no app.','Sem anuidade','["Sem anuidade para sempre","Controle total pelo aplicativo","Limite que cresce com o uso","Pix, boletos e transferências sem custo"]','["Sem anuidade","Mais popular"]',4.7,'https://www.nubank.com.br','Pedir cartão','Sem anuidade',1,0,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('inter-gold','Inter Gold','Banco Inter',NULL,'Conta e cartão gratuitos com pontos no Inter Loop.','Sem anuidade','["Sem anuidade","Pontos no programa Inter Loop","Cashback no Inter Shop","Conta global em dólar e euro"]','["Sem anuidade","Cashback"]',4.6,'https://www.inter.co','Pedir cartão','Cashback',1,1,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('c6-bank','C6 Bank','C6 Bank',NULL,'Acumula pontos no Átomos e personaliza o seu cartão.','Sem anuidade','["Sem anuidade","Pontos no programa Átomos","Transfere para Smiles, LATAM Pass e Livelo","Cartão personalizável"]','["Sem anuidade","Milhas"]',4.5,'https://www.c6bank.com.br','Pedir cartão','Milhas',1,2,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('xp-visa-infinite','XP Visa Infinite','XP',NULL,'Infinite sem anuidade investindo na XP, com salas VIP.','Sem anuidade investindo na XP','["Sem anuidade investindo na XP","1% de cashback ou pontos","Acessos a salas VIP (Dragon Pass)","Bandeira Visa Infinite"]','["Premium","Salas VIP"]',4.6,'https://www.xpi.com.br','Pedir cartão','Premium',1,3,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('nubank-ultravioleta','Nubank Ultravioleta','Nubank',NULL,'A versão premium do Nubank, com cashback que rende.','A partir de R$ 49/mês','["1% de cashback que rende 200% do CDI","Priority Pass com acessos a salas VIP","Cartão metálico","Atendimento exclusivo"]','["Cashback","Premium"]',4.5,'https://www.nubank.com.br/ultravioleta','Pedir cartão','Cashback',0,4,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('santander-unique','Santander Unique','Santander',NULL,'Alta pontuação na Esfera e benefícios completos de viagem.','Com anuidade (consulte isenção)','["Ate 3 pontos por dolar na Esfera","Salas VIP em aeroportos","Mastercard Black ou Visa Infinite","Seguros e assistencias de viagem"]','["Milhas","Premium"]',4.3,'https://www.santander.com.br','Ver oferta','Milhas',0,5,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('itau-click-platinum','Itaú Click Platinum','Itaú',NULL,'Platinum sem anuidade, com pontos e seguros inclusos.','Sem anuidade','["Sem anuidade","Pontos no programa de recompensas","Seguros e assistencias","Disponivel em Visa ou Mastercard"]','["Sem anuidade"]',4.2,'https://www.itau.com.br','Pedir cartão','Sem anuidade',0,6,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('bradesco-amazon','Cartão Amazon Bradesco','Bradesco',NULL,'Cashback turbinado nas compras da Amazon.','Sem anuidade','["Ate 5% de cashback na Amazon","2% em restaurantes, farmacias e viagens","Sem anuidade","Bandeira Visa"]','["Cashback","Sem anuidade"]',4.4,'https://www.bradescocartoes.com.br','Pedir cartão','Cashback',0,7,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('latam-pass-itau','LATAM Pass Itaú','Itaú',NULL,'Acumula LATAM Pass e voa mais longe.','Com anuidade (isenção por gasto)','["Ate 2,5 pontos LATAM Pass por dolar","Salas VIP em aeroportos","Pontos que nao expiram","Beneficios LATAM"]','["Milhas"]',4.3,'https://www.itau.com.br','Ver oferta','Milhas',0,8,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('picpay','PicPay','PicPay',NULL,'Cartão integrado à carteira PicPay com cashback.','Sem anuidade','["Sem anuidade","Cashback em promocoes","Saldo que rende","Tudo no app PicPay"]','["Sem anuidade","Cashback"]',4.1,'https://www.picpay.com','Pedir cartão','Cashback',0,9,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('pagbank','PagBank','PagBank',NULL,'Cartão do PagBank com saldo rendendo todo dia.','Sem anuidade','["Sem anuidade","Saldo rende 100% do CDI","Cashback em compras","Aprovacao facilitada"]','["Sem anuidade"]',4.0,'https://www.pagbank.com.br','Pedir cartão','Cashback',0,10,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('mercado-pago','Mercado Pago','Mercado Pago',NULL,'Cartão do Mercado Pago com cashback no Mercado Livre.','Sem anuidade','["Sem anuidade","Cashback no Mercado Livre","Saldo que rende","Bandeira Visa ou Mastercard"]','["Sem anuidade","Cashback"]',4.2,'https://www.mercadopago.com.br','Pedir cartão','Cashback',0,11,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('will-bank','Will Bank','Will Bank',NULL,'Cartão simples e fácil de aprovar, sem complicação.','Sem anuidade','["Sem anuidade","Aprovacao facilitada","Will Mais com descontos","Tudo pelo aplicativo"]','["Sem anuidade","Aprovação fácil"]',4.0,'https://www.willbank.com.br','Pedir cartão','Iniciantes',0,12,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('neon','Neon','Neon',NULL,'Conta e cartão sem tarifas, com limite que você constrói.','Sem anuidade','["Sem anuidade","Cartao multiplo (credito e debito)","Invista e aumente o limite","Opcao garantida para comecar"]','["Sem anuidade","Iniciantes"]',4.0,'https://www.neon.com.br','Pedir cartão','Iniciantes',0,13,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('digio','Digio','Digio',NULL,'Cartão digital simples com cashback em parceiros.','Sem anuidade','["Sem anuidade","Cashback em parceiros","Aprovacao 100% digital","Bandeira Visa ou Mastercard"]','["Sem anuidade"]',3.9,'https://www.digio.com.br','Pedir cartão','Iniciantes',0,14,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('magalu','Cartão Magalu','Magalu',NULL,'Cashback nas compras do Magazine Luiza.','Sem anuidade','["Ate 2% de cashback no Magalu","Sem anuidade","Parcelamento facilitado","Ofertas exclusivas"]','["Cashback","Sem anuidade"]',4.0,'https://www.magazineluiza.com.br','Pedir cartão','Cashback',0,15,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('santander-sx','Santander SX','Santander',NULL,'Cartão para começar, com isenção de anuidade pelo uso.','Sem anuidade (com uso)','["Anuidade isenta usando o cartao","Programa de pontos","Bandeira internacional","Ideal para quem esta comecando"]','["Iniciantes","Sem anuidade"]',3.9,'https://www.santander.com.br','Pedir cartão','Iniciantes',0,16,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('ourocard-bb','Ourocard Banco do Brasil','Banco do Brasil',NULL,'A tradição do BB com pontos Livelo e opções para todo perfil.','Varia conforme o cartão','["Pontos Livelo","Diversas bandeiras e versoes","Ampla rede de atendimento","Opcoes premium com salas VIP"]','["Milhas","Tradicional"]',4.0,'https://www.bb.com.br','Ver oferta','Milhas',0,17,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('amex-platinum','American Express Platinum','American Express',NULL,'Para quem quer o topo em viagens, serviços e experiências.','Anuidade premium (consulte)','["Salas VIP ilimitadas (Priority Pass)","Ate 3 pontos Membership Rewards","Fine Hotels & Resorts","Concierge e seguros completos"]','["Premium","Salas VIP"]',4.4,'https://www.americanexpress.com/br','Ver oferta','Premium',0,18,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000)),
('azul-itaucard-infinite','Azul Itaucard Infinite','Itaú / Azul',NULL,'Acumula TudoAzul e voa com prioridade.','Com anuidade (isenção por gasto)','["Ate 3 pontos TudoAzul por dolar","Salas VIP em aeroportos","Beneficios do Clube TudoAzul","Prioridade em voos Azul"]','["Milhas","Premium"]',4.2,'https://www.itau.com.br','Ver oferta','Milhas',0,19,1,(strftime('%s','now')*1000),(strftime('%s','now')*1000));
